import time
import os
import re
import json
import asyncio
import argparse
from config import *  # 引入所有配置
from utils import read_file, read_json, add_line_numbers
from defect_patterns import PATTERN_REGEX, PATTERNS
from code_parser import extract_variable_operations, annotate_code
from api_client import APIClient
# 只在本地模型模式下导入LocalModel
if MODEL_TYPE == "local":
    from model_loader import LocalModel
from output import save_response
from tqdm import tqdm
try:
    import torch
except ImportError:
    torch = None
from agent.conversation_manager import ConversationManager
from agent.plan_agent import PlanAgent  # 添加PlanAgent导入
from agent.workflow_manager import WorkflowManager, create_workflow_manager  # 添加WorkflowManager导入

def generate_project_analysis_report(project_structure, dependency_analysis, plan_result, args):
    """生成项目级别分析报告"""
    report = f"""# Project Analysis Report

## Project Information
- **Project Path**: {args.project_path}
- **Merge Strategy**: {args.merge_strategy}
- **Analysis Date**: {time.strftime('%Y-%m-%d %H:%M:%S')}

## Project Structure Summary
- **Total Files**: {len(project_structure['c_files']) + len(project_structure['h_files'])}
- **C Source Files**: {len(project_structure['c_files'])}
- **Header Files**: {len(project_structure['h_files'])}
- **Total Size**: {project_structure['total_size']} bytes
- **Main Function Files**: {len(project_structure['main_files'])}

### Largest Files
"""
    
    for file_path, size in project_structure['largest_files'][:5]:
        rel_path = os.path.relpath(file_path, args.project_path)
        report += f"- {rel_path}: {size} bytes\n"
    
    if project_structure['main_files']:
        report += f"\n### Main Function Files\n"
        for main_file in project_structure['main_files']:
            rel_path = os.path.relpath(main_file, args.project_path)
            report += f"- {rel_path}\n"
    
    # 依赖分析部分
    report += f"""
## Cross-File Dependency Analysis
- **Global Variables Found**: {len(dependency_analysis['symbol_table']['globals'])}
- **Functions Defined**: {len(dependency_analysis['symbol_table']['functions'])}
- **Cross-File Race Risks**: {len(dependency_analysis['cross_file_race_risks'])}

### Potential Race Conditions
"""
    
    for risk in dependency_analysis['cross_file_race_risks'][:10]:  # 最多显示10个
        report += f"- **{risk['variable']}** ({risk['risk_level']} Risk): {risk['description']}\n"
    
    # Plan Agent分析结果
    report += f"""
## Plan Agent Analysis Results
- **Tools Used**: {', '.join(plan_result['used_tools'])}
- **Tool Execution Sequence**: {', '.join(plan_result['tool_sequence'])}

### Analysis Facts
"""
    
    if 'facts' in plan_result and plan_result['facts']:
        for tool_name, facts in plan_result['facts'].items():
            if isinstance(facts, dict) and facts:
                report += f"\n#### {tool_name} Results\n"
                # 简化显示facts内容
                for key, value in list(facts.items())[:3]:  # 只显示前3个键值对
                    if isinstance(value, (str, int, float)):
                        report += f"- {key}: {value}\n"
                    elif isinstance(value, list) and len(value) < 10:
                        report += f"- {key}: {len(value)} items\n"
    
    report += f"""
## Recommendations

Based on the analysis results:

1. **Code Structure**: The project contains {len(project_structure['c_files'])} C files with {len(dependency_analysis['cross_file_race_risks'])} potential race conditions detected.

2. **Tool Usage**: The analysis used {len(plan_result['used_tools'])} static analysis tools in the following order: {' → '.join(plan_result['tool_sequence'])}.

3. **Risk Assessment**: 
   - HIGH risk variables: {len([r for r in dependency_analysis['cross_file_race_risks'] if r['risk_level'] == 'HIGH'])}
   - MEDIUM risk variables: {len([r for r in dependency_analysis['cross_file_race_risks'] if r['risk_level'] == 'MEDIUM'])}

4. **Next Steps**: Review the highlighted race conditions and consider adding proper synchronization mechanisms.

---
*Report generated by Clover Project Analysis Tool*
"""
    
    return report

# 异步处理单个缺陷模式任务（使用ConversationManager）
async def handle_pattern_task(defect_mode, context, api_client, model, start_time):
    print(f"[Debug] 进入handle_pattern_task: defect_mode={defect_mode}")
    
    # 创建对话管理器
    conversation_manager = ConversationManager(api_client, model)
    
    # 使用对话管理器运行对话
    return await conversation_manager.run_conversation(defect_mode, context, start_time)

# 异步处理批量缺陷模式任务（使用ConversationManager）
async def handle_batch_tasks(defect_modes, contexts, api_client, model, start_time):
    print(f"[Debug] 进入handle_batch_tasks: 批量处理 {len(defect_modes)} 个缺陷模式任务")
    
    # 创建对话管理器
    conversation_manager = ConversationManager(api_client, model)
    
    # 使用对话管理器运行对话
    return await conversation_manager.run_batch_conversation(defect_modes, contexts, start_time)

# 异步处理Plan Agent任务
async def handle_plan_task(code_str, api_client, model, input_file_name="input.c", force_local_tools=False):
    print(f"[Debug] 进入handle_plan_task: 使用Plan Agent分析代码")
    
    try:
        # 创建Plan Agent
        # 确保api_client和model都不为空
        if not api_client:
            raise ValueError("api_client不能为空")
        
        # 如果model为None，使用api_client默认模型
        if model is None and api_client.model_type == "online":
            # 使用为Plan Agent配置的模型
            model = AGENT_MODELS.get("plan", api_client.model)
            
        # 确定原始文件名，确保使用绝对路径
        original_file_name = os.path.abspath(input_file_name) if input_file_name else None
        
        # 检查文件是否存在
        if original_file_name and not os.path.exists(original_file_name):
            print(f"[Warning] 文件不存在: {original_file_name}")
            # 尝试其他可能的路径
            possible_paths = [
                os.path.join(os.getcwd(), input_file_name),
                os.path.join(BASE_SRC_PATH, os.path.basename(input_file_name)),
                os.path.join(BASE_SRC_PATH, "Racebench_2.1", f"svp_simple_{os.path.basename(input_file_name).split('_')[2]}", os.path.basename(input_file_name))
            ]
            
            for path in possible_paths:
                if os.path.exists(path):
                    original_file_name = path
                    print(f"[Debug] 找到文件: {original_file_name}")
                    break
        
        print(f"[Debug] 使用原始文件名: {original_file_name}")
            
        plan_agent = PlanAgent(api_client, model or "default_model", original_file_name=original_file_name)
        
        # 使用Plan Agent分析代码
        plan_result = await plan_agent.decide_tools(code_str)
        
        # 输出Plan Agent分析结果
        print(f"[Debug] Plan Agent分析完成，使用了 {len(plan_result['used_tools'])} 个工具")
        print(f"[Debug] 工具执行顺序: {', '.join(plan_result.get('tool_sequence', []))}")
        
        # 先检查Plan Agent是否已经生成了有效的expert-judge计划
        existing_expert_judge_json = plan_result.get("expert_judge_json", "{}")
        expert_judge_json = existing_expert_judge_json
        
        # 解析现有的任务数量
        existing_task_count = 0
        try:
            if existing_expert_judge_json and existing_expert_judge_json != "{}":
                existing_data = json.loads(existing_expert_judge_json)
                existing_task_count = len(existing_data.get("expert_judge_tasks", []))
        except:
            existing_task_count = 0
        
        # 如果Plan Agent没有生成有效任务且有Defect_Highlight结果，尝试新的任务规划方法
        highlight_results = plan_result.get("facts", {}).get("Defect_Highlight", {})
        if existing_task_count == 0 and highlight_results and highlight_results.get("defects"):
            print(f"[Debug] Plan Agent未生成任务且检测到Defect_Highlight结果，使用新的任务规划方法")
            try:
                # 使用新的create_task_plan方法
                new_expert_judge_json = await plan_agent.create_task_plan(highlight_results)
                # 验证新方法是否生成了有效任务
                new_data = json.loads(new_expert_judge_json)
                new_task_count = len(new_data.get("expert_judge_tasks", []))
                if new_task_count > 0:
                    expert_judge_json = new_expert_judge_json
                    print(f"[Debug] 新任务规划方法成功生成{new_task_count}个expert-judge任务")
                else:
                    print(f"[Debug] 新任务规划方法未生成有效任务，保持原有结果")
            except Exception as e:
                print(f"[Warning] 新任务规划方法失败，保持原有结果: {str(e)}")
        elif existing_task_count > 0:
            print(f"[Debug] Plan Agent已生成{existing_task_count}个expert-judge任务，使用现有结果")
        else:
            print(f"[Debug] 未检测到Defect_Highlight结果，将使用传统方法生成expert-judge计划")
        
        # 提取工具使用计划
        tool_plan = plan_result.get("tool_plan_output", "")
        # 记录原始工具计划
        print(f"[Debug] 原始工具计划: {tool_plan[:100]}...")
        
        # 增强提取工具计划的能力
        tool_plan_text = "<tool>\n未能获取工具计划\n</tool>"
        try:
            # 如果工具计划已经是格式化的，直接使用
            if tool_plan and "<tool>" in tool_plan and "</tool>" in tool_plan:
                tool_plan_text = tool_plan
                print(f"[Debug] 使用原始工具计划")
            else:
                # 尝试多种模式提取工具计划
                tool_patterns = [
                    r"<tool>(.*?)</tool>",  # 标准格式
                    r"```(?:xml|html)?\s*<tool>(.*?)</tool>\s*```",  # 代码块中的格式
                    r"<tool>\s*([\s\S]*?)\s*</tool>"  # 更宽松的匹配
                ]
                
                for pattern in tool_patterns:
                    tool_matches = re.findall(pattern, tool_plan, re.DOTALL)
                    if tool_matches:
                        tool_plan_text = f"<tool>\n{tool_matches[0].strip()}\n</tool>"
                        print(f"[Debug] 成功提取工具计划，使用模式: {pattern}")
                        break
            
            # 检查是否成功提取了工具计划
            if tool_plan_text == "<tool>\n未能获取工具计划\n</tool>":
                # 检查plan_result中是否有tool_sequence
                if "tool_sequence" in plan_result and plan_result["tool_sequence"]:
                    tool_sequence = plan_result["tool_sequence"]
                    tool_plan_text = "<tool>\n" + "\n".join(tool_sequence) + "\n</tool>"
                    print(f"[Debug] 从tool_sequence生成工具计划: {tool_plan_text}")
                else:
                    print(f"[Debug] 无法从原始工具计划中提取内容，使用默认文本")
        except Exception as e:
            print(f"[Error] 提取工具计划失败: {str(e)}")
        
        # 将工具计划保存到plan_result
        plan_result["tool_plan_text"] = tool_plan_text
        
        # 如果仍然没有有效的expert-judge计划，从plan_result中提取
        current_task_count = 0
        try:
            if expert_judge_json and expert_judge_json != "{}":
                current_data = json.loads(expert_judge_json)
                current_task_count = len(current_data.get("expert_judge_tasks", []))
        except:
            current_task_count = 0
            
        if current_task_count == 0:
            try:
                # 尝试从plan_result中获取expert-judge计划
                if "expert_judge_plan" in plan_result and plan_result["expert_judge_plan"]:
                    expert_judge_json = plan_result["expert_judge_plan"]
                    print(f"[Debug] 从plan_result中提取expert-judge计划")
                else:
                    # 如果没有expert-judge计划，使用空对象
                    expert_judge_data = {"expert_judge_tasks": []}
                    expert_judge_json = json.dumps(expert_judge_data, indent=2, ensure_ascii=False)
                    print(f"[Debug] 未找到任何expert-judge计划，使用空任务列表")
            except Exception as e:
                print(f"[Debug] 无法解析expert-judge计划: {str(e)}")
                print(f"[Warning] 解析expert-judge任务失败: {str(e)}")
                expert_judge_json = "{}"
        
        # 解析expert-judge计划，获取任务数量和变量数量
        try:
            expert_judge_data = json.loads(expert_judge_json)
            expert_judge_tasks = expert_judge_data.get("expert_judge_tasks", [])
            var_count = sum(len(task.get("sharedVariables", [])) for task in expert_judge_tasks)
            print(f"[Debug] 加载了 {len(expert_judge_tasks)} 个expert-judge任务，涉及 {var_count} 个共享变量")
        except Exception as e:
            print(f"[Debug] 无法解析expert-judge计划: {str(e)}")
            expert_judge_json = "{}"  # 重置为空JSON对象
        
        # 将两轮输出保存到单独的文件中
        plan_result["tool_plan_text"] = tool_plan_text
        plan_result["expert_judge_json"] = expert_judge_json
        
        return plan_result
    except Exception as e:
        print(f"[Error] Plan Agent分析失败: {str(e)}")
        # 返回一个空的结果，避免程序崩溃
        return {
            "facts": {},
            "used_tools": [],
            "tool_sequence": [],
            "tool_plan_text": "<tool>\n未能获取工具计划\n</tool>",
            "expert_judge_json": "{}"
        }

async def main():
    # 解析命令行参数
    parser = argparse.ArgumentParser(description="Clover - 代码分析工具")
    parser.add_argument("--force-local-tools", action="store_true", help="强制使用本地工具而不是模拟输出")
    parser.add_argument("--project-path", type=str, help="项目目录路径（用于项目级别分析）")
    parser.add_argument("--merge-strategy", type=str, choices=["smart", "full", "summary", "main_only"], 
                       default="smart", help="项目模式下的代码合并策略")
    parser.add_argument("--single-file", type=str, help="单文件分析路径")
    parser.add_argument("--max-lines", type=int, default=5000, help="单文件分析最大行数限制（默认5000行）")
    parser.add_argument("--max-total-lines", type=int, default=10000, help="项目模式合并代码最大总行数（默认10000行）")
    args = parser.parse_args()
    
    # 清理GPU缓存（如果torch可用的话）
    if torch is not None and torch.cuda.is_available():
        torch.cuda.empty_cache()
    print(f"[Debug] 程序开始执行，Python版本={os.sys.version}")
    print(f"[Debug] 开始执行main函数")
    if args.force_local_tools:
        print(f"[Debug] 强制使用本地工具模式已启用")
    
    # 检查运行模式
    if args.project_path:
        print(f"[Debug] 项目模式启用，项目路径: {args.project_path}")
        print(f"[Debug] 代码合并策略: {args.merge_strategy}")
        return await handle_project_mode(args)
    elif args.single_file:
        print(f"[Debug] 单文件模式启用，文件路径: {args.single_file}")
        return await handle_single_file_mode(args)
    else:
        print(f"[Debug] 默认批量模式启用")
        return await handle_batch_mode(args)

async def handle_project_mode(args):
    """处理项目模式分析"""
    from preprocessing.core.project_scanner import ProjectScanner
    from preprocessing.analyzers.cross_file_analyzer import CrossFileAnalyzer
    from preprocessing.core.code_merger import CodeMerger
    
    try:
        # 验证项目路径
        if not os.path.exists(args.project_path):
            print(f"[Error] 项目路径不存在: {args.project_path}")
            return
        
        if not os.path.isdir(args.project_path):
            print(f"[Error] 项目路径不是目录: {args.project_path}")
            return
        
        print(f"[Debug] 开始项目级别分析")
        
        # 初始化API客户端
        api_client = APIClient()
        if args.force_local_tools:
            api_client.set_force_local_tools(True)
        
        # 获取模型
        local_model = api_client.local_model if api_client.model_type == "local" else None
        plan_model = AGENT_MODELS.get("plan", api_client.model) if api_client.model_type == "online" else local_model
        
        # 创建输出目录
        project_name = os.path.basename(args.project_path.rstrip('/'))
        project_response_path = os.path.join(RESPONSE_PATH, f"project_{project_name}")
        os.makedirs(project_response_path, exist_ok=True)
        
        # 1. 项目扫描和依赖分析
        print(f"[Debug] 开始项目扫描和依赖分析")
        scanner = ProjectScanner(args.project_path)
        cross_analyzer = CrossFileAnalyzer(args.project_path)
        
        # 创建代码合并器（使用用户指定的行数限制）
        merger = CodeMerger(max_total_lines=args.max_total_lines)
        
        # 保存项目结构分析
        project_structure = scanner.analyze_project_structure()
        structure_file = os.path.join(project_response_path, "project_structure.json")
        with open(structure_file, "w", encoding='utf-8') as f:
            json.dump(project_structure, f, indent=2, ensure_ascii=False)
        
        # 保存跨文件依赖分析
        dependency_analysis = cross_analyzer.analyze_project_dependencies()
        dependency_file = os.path.join(project_response_path, "dependency_analysis.json")
        with open(dependency_file, "w", encoding='utf-8') as f:
            json.dump(dependency_analysis, f, indent=2, ensure_ascii=False)
        
        # 生成依赖报告
        dependency_report = cross_analyzer.get_dependency_report()
        report_file = os.path.join(project_response_path, "dependency_report.md")
        with open(report_file, "w", encoding='utf-8') as f:
            f.write(dependency_report)
        
        print(f"[Debug] 项目分析完成，结果保存到: {project_response_path}")
        print(f"  - C文件数量: {len(project_structure['c_files'])}")
        print(f"  - 头文件数量: {len(project_structure['h_files'])}")
        print(f"  - 总大小: {project_structure['total_size']} 字节")
        print(f"  - 主函数文件: {len(project_structure['main_files'])}")
        
        # 2. 使用Plan Agent进行项目级别分析
        print(f"[Debug] 开始Plan Agent项目级别分析")
        plan_agent = PlanAgent(api_client, plan_model, 
                              original_file_name=None, 
                              project_path=args.project_path)
        
        # 执行项目级别工具决策（代码会在PlanAgent内部自动合并）
        plan_result = await plan_agent.decide_tools(code=None, merge_strategy=args.merge_strategy)
        
        # 保存Plan Agent分析结果
        plan_result_file = os.path.join(project_response_path, "plan_analysis.json")
        with open(plan_result_file, "w", encoding='utf-8') as f:
            json.dump(plan_result, f, indent=2, ensure_ascii=False)
        
        print(f"[Debug] Plan Agent分析完成")
        print(f"  - 使用工具: {', '.join(plan_result['used_tools'])}")
        print(f"  - 工具序列: {', '.join(plan_result['tool_sequence'])}")
        
        # 3. 生成项目级别分析报告
        final_report = generate_project_analysis_report(
            project_structure, dependency_analysis, plan_result, args
        )
        
        final_report_file = os.path.join(project_response_path, "project_analysis_report.md")
        with open(final_report_file, "w", encoding='utf-8') as f:
            f.write(final_report)
        
        print(f"[Success] 项目级别分析完成，所有结果保存到: {project_response_path}")
        return plan_result
        
    except Exception as e:
        print(f"[Error] 项目模式分析失败: {str(e)}")
        import traceback
        traceback.print_exc()

async def handle_single_file_mode(args):
    """处理单文件模式分析"""
    try:
        if not os.path.exists(args.single_file):
            print(f"[Error] 文件不存在: {args.single_file}")
            return
        
        print(f"[Debug] 开始单文件分析: {args.single_file}")
        
        # 读取文件内容
        code_content = read_file(args.single_file)
        code_lines = code_content.splitlines()
        
        # 检查文件大小并应用行数限制
        total_lines = len(code_lines)
        max_lines = args.max_lines
        
        if total_lines > max_lines:
            print(f"[Warning] 文件过大({total_lines}行)，将截取前{max_lines}行进行分析")
            code_lines = code_lines[:max_lines]
            # 添加截取说明
            code_lines.append(f"")
            code_lines.append(f"// [CLOVER_TRUNCATED] 文件被截取，原始文件总共{total_lines}行，此处只显示前{max_lines}行")
        else:
            print(f"[Debug] 文件大小适中({total_lines}行)，进行完整分析")
        
        code_with_lines = add_line_numbers(code_lines)
        code_str = "\n".join(code_with_lines)
        
        # 初始化API客户端
        api_client = APIClient()
        if args.force_local_tools:
            api_client.set_force_local_tools(True)
        
        # 获取模型
        local_model = api_client.local_model if api_client.model_type == "local" else None
        plan_model = AGENT_MODELS.get("plan", api_client.model) if api_client.model_type == "online" else local_model
        
        # 使用Plan Agent分析
        plan_agent = PlanAgent(api_client, plan_model, original_file_name=args.single_file)
        plan_result = await plan_agent.decide_tools(code_str)
        
        # 添加文件分析元数据
        plan_result["file_metadata"] = {
            "original_file": args.single_file,
            "total_lines": total_lines,
            "analyzed_lines": len(code_lines) - (2 if total_lines > max_lines else 0),  # 减去添加的说明行
            "truncated": total_lines > max_lines,
            "max_lines_limit": max_lines,
            "file_size_bytes": os.path.getsize(args.single_file)
        }
        
        # 保存Plan Agent结果
        file_name = os.path.basename(args.single_file)
        plan_response_file = os.path.join(RESPONSE_PATH, f"{file_name}_plan_analysis.json")
        with open(plan_response_file, "w", encoding='utf-8') as f:
            json.dump(plan_result, f, indent=2, ensure_ascii=False)
        
        print(f"[Debug] Plan Agent分析完成，结果保存到: {plan_response_file}")
        
        # 检查是否有expert-judge任务需要执行
        expert_judge_tasks = []
        try:
            if plan_result.get("expert_judge_json"):
                expert_judge_data = json.loads(plan_result["expert_judge_json"])
                expert_judge_tasks = expert_judge_data.get("expert_judge_tasks", [])
        except Exception as e:
            print(f"[Warning] 解析expert-judge任务失败: {str(e)}")
        
        # 保存expert-judge计划文件（如果有任务的话）
        if expert_judge_tasks:
            expert_judge_plan_file = os.path.join(RESPONSE_PATH, f"{file_name}_expert-judge-plan.json")
            try:
                expert_judge_plan_data = json.loads(plan_result["expert_judge_json"])
                with open(expert_judge_plan_file, "w", encoding='utf-8') as f:
                    json.dump(expert_judge_plan_data, f, indent=2, ensure_ascii=False)
                print(f"[Debug] Expert-judge计划保存到: {expert_judge_plan_file}")
            except Exception as e:
                print(f"[Warning] 保存expert-judge计划失败: {str(e)}")
        
        # 如果有expert-judge任务，执行Expert-Judge对话
        expert_judge_results = {}
        if expert_judge_tasks:
            print(f"[Debug] 发现 {len(expert_judge_tasks)} 个expert-judge任务，开始执行Expert-Judge对话")
            
            # 为Expert和Judge Agent选择模型
            expert_judge_model = None
            if api_client.model_type == "online":
                expert_judge_model = AGENT_MODELS.get("plan", api_client.model)
            else:
                expert_judge_model = local_model
            
            # 构建分析上下文
            context_base = {
                "variables_text": "",  # 单文件模式没有特定变量
                "operations_text": "",  # 单文件模式没有特定操作
                "code_str": code_str,
                "plan_facts": plan_result["facts"],
                "expert_judge_tasks": expert_judge_tasks
            }
            
            # 记录任务开始时间
            start_time = time.time()
            
            # 为每个任务创建缺陷模式分析
            for i, task in enumerate(expert_judge_tasks):
                # 从任务的accessPattern推断缺陷模式代码
                access_pattern = task.get("accessPattern", [])
                if access_pattern == ["Read", "Write", "Read"]:
                    defect_mode = "RWR"
                elif access_pattern == ["Read", "Write", "Write"]:
                    defect_mode = "RWW"
                elif access_pattern == ["Write", "Write", "Read"]:
                    defect_mode = "WWR"
                elif access_pattern == ["Write", "Read", "Write"]:
                    defect_mode = "WRW"
                else:
                    defect_mode = "RWR"  # 默认使用RWR模式
                
                task_id = f"expert_judge_task_{i+1}"
                pattern_response_file = os.path.join(RESPONSE_PATH, f"{file_name}_{task_id}_response.txt")
                context = context_base.copy()
                context["response_file_path"] = pattern_response_file
                
                # 将任务信息添加到上下文中，让Expert Agent知道要分析的变量
                # 兼容新旧两种任务格式
                task_vars = task.get("sharedVariables", [])  # 传统格式
                if not task_vars:
                    task_vars = task.get("variables", [])  # 新格式
                
                if task_vars:
                    context["variables_text"] = ", ".join(task_vars)
                    # 从Operation_Analyzer结果中筛选出相关的操作信息
                    relevant_operations = []
                    rw_data = plan_result.get("facts", {}).get("Operation_Analyzer", {})
                    for access in rw_data.get("MAIN_INFO", []) + rw_data.get("ISR_INFO", []):
                        if access.get("variable") in task_vars:
                            relevant_operations.append(f"Line {access.get('line')}: {access.get('operation')} {access.get('variable')} in {access.get('function')}")
                    context["operations_text"] = "\n".join(relevant_operations)
                    
                    # 从Defect_Highlight结果中筛选出相关的defect信息
                    defect_data = plan_result.get("facts", {}).get("Defect_Highlight", {})
                    all_defects = defect_data.get("defects", [])
                    task_defects = []
                    
                    for defect in all_defects:
                        shared_variable = defect.get("sharedVariable", "")
                        if shared_variable in task_vars:
                            task_defects.append(defect)
                    
                    # 格式化defect信息
                    if task_defects:
                        defect_lines = ["Defect Highlight Results for assigned variables:"]
                        for j, defect in enumerate(task_defects, 1):
                            variable = defect.get("sharedVariable", "unknown")
                            defect_type = defect.get("type", "unknown")
                            access_pattern = defect.get("accessPattern", [])
                            lines = defect.get("lines", [])
                            
                            defect_lines.append(f"  Defect {j}:")
                            defect_lines.append(f"    Variable: {variable}")
                            defect_lines.append(f"    Type: {defect_type}")
                            defect_lines.append(f"    Access Pattern: {' -> '.join(access_pattern)}")
                            defect_lines.append(f"    Line Numbers: {', '.join(map(str, lines))}")
                            defect_lines.append("")
                        
                        context["defects_text"] = "\n".join(defect_lines)
                    else:
                        context["defects_text"] = "No specific defects highlighted for the assigned variables."
                
                try:
                    # 调用Expert-Judge对话，使用正确的缺陷模式
                    print(f"[Debug] 执行expert-judge任务 {i+1}/{len(expert_judge_tasks)}: {defect_mode} for variables {task_vars}")
                    result = await handle_pattern_task(defect_mode, context, api_client, expert_judge_model, start_time)
                    expert_judge_results[task_id] = result
                    print(f"[Debug] Expert-judge任务 {i+1} 完成，结果保存到: {pattern_response_file}")
                except Exception as e:
                    print(f"[Error] Expert-judge任务 {i+1} 执行失败: {str(e)}")
                    expert_judge_results[task_id] = {"error": str(e)}
        else:
            print(f"[Info] 没有发现expert-judge任务，跳过Expert-Judge对话")
        
        # 合并所有结果
        final_result = {
            "plan_analysis": plan_result,
            "expert_judge_results": expert_judge_results,
            "file_metadata": plan_result["file_metadata"]
        }
        
        # 保存最终结果
        final_response_file = os.path.join(RESPONSE_PATH, f"{file_name}_complete_analysis.json")
        with open(final_response_file, "w", encoding='utf-8') as f:
            json.dump(final_result, f, indent=2, ensure_ascii=False)
        
        # 输出分析摘要
        print(f"[Success] 单文件完整分析完成，结果保存到: {final_response_file}")
        print(f"  - 原始文件: {args.single_file}")
        print(f"  - 文件大小: {plan_result['file_metadata']['file_size_bytes']} 字节")
        print(f"  - 总行数: {total_lines}")
        print(f"  - 分析行数: {plan_result['file_metadata']['analyzed_lines']}")
        print(f"  - Expert-Judge任务: {len(expert_judge_tasks)} 个")
        if plan_result['file_metadata']['truncated']:
            print(f"  - 状态: 文件被截取（超过{max_lines}行限制）")
        else:
            print(f"  - 状态: 完整分析")
        
        return final_result
        
    except Exception as e:
        print(f"[Error] 单文件模式分析失败: {str(e)}")
        import traceback
        traceback.print_exc()

async def handle_batch_mode(args):
    """处理批量模式分析（原有逻辑）"""
    results = []
    max_time = 0
    log_file_path = os.path.join(RESPONSE_PATH, "max_time_log.txt")
    
    # 创建响应目录
    os.makedirs(RESPONSE_PATH, exist_ok=True)
    print(f"[Debug] 响应目录已创建: {RESPONSE_PATH}")
    
    # 初始化API客户端
    print(f"[Debug] 开始初始化API客户端")
    api_client = APIClient()
    
    # 设置是否强制使用本地工具
    if args.force_local_tools:
        api_client.set_force_local_tools(True)
        
    print(f"[Debug] API客户端初始化完成，模型类型={api_client.model_type}")
    
    # 打印API密钥状态
    if api_client.model_type == "online":
        api_client.print_api_keys_status()
    
    # 获取本地模型
    local_model = api_client.local_model if api_client.model_type == "local" else None
    if local_model:
        # 测试模型是否能响应简单提示词
        print(f"[Debug] 开始测试模型基本功能")
        test_prompt = "Hello, this is a test prompt. Please respond with one sentence."
        try:
            test_response = await local_model.generate_responses(
                prompt=test_prompt, 
                max_tokens=50
            )
            print(f"[Debug] 模型测试成功，响应: {str(test_response)[:100]}...")
        except Exception as e:
            print(f"[Error] 模型测试失败: {str(e)}")
    else:
        print(f"[Debug] 未使用本地模型")

    try:
        # 处理案例（示例：i=1）
        for i in range(3,4):
            j = 1
            file_template = f"{BASE_SRC_PATH}/Racebench_2.1/svp_simple_{{:03d}}/svp_simple_{{:03d}}_{{:03d}}"
            defect_file_path = file_template.format(i, i, j) + "-output_defects.txt"
            json_file_path = file_template.format(i, i, j) + "-output.json"
            code_file_path = file_template.format(i, i, j) + ".c"
            response_file_name = os.path.basename(code_file_path).replace(".c", "-response.txt")
            response_file_base = os.path.join(RESPONSE_PATH, response_file_name)

            # 读取文件内容
            try:
                print(f"[Debug] 开始读取文件内容")
                content = read_file(defect_file_path)
                json_data = read_json(json_file_path)
                code_lines = read_file(code_file_path).splitlines()
                print(f"[Debug] 文件读取成功: 缺陷内容长度={len(content)}, 代码行数={len(code_lines)}")
            except Exception as e:
                print(f"[Critical Error] 读取文件失败 (i={i}): {str(e)}")
                continue

            # 提取缺陷模式和变量信息
            code_with_lines = add_line_numbers(code_lines)
            reports = content.split("---")
            all_variables = set()
            all_operations = {}
            found_defect_modes = set()
            
            print(f"[Debug] 开始提取缺陷模式，报告数量={len(reports)}")
            for report in reports:
                matches = re.findall(PATTERN_REGEX, report)
                for match in matches:
                    defect_mode, variable, location = match
                    all_variables.add(variable)
                    found_defect_modes.add(defect_mode)
                    operations = extract_variable_operations(variable, json_data)
                    all_operations.setdefault(variable, []).extend(operations)
            
            print(f"[Debug] 缺陷模式提取完成: {found_defect_modes}")
            if not found_defect_modes:
                print(f"[Info] No defect modes found (i={i})")
                continue

            # 构建分析上下文
            variables_text = ", ".join(sorted(all_variables))
            unique_operations = []
            for var in sorted(all_variables):
                unique_operations.extend(list(dict.fromkeys(all_operations.get(var, []))))
            operations_text = "\n".join(unique_operations)
            annotated_code = annotate_code(code_with_lines, unique_operations)
            code_str = "\n".join(annotated_code)

            context_base = {
                "variables_text": variables_text,
                "operations_text": operations_text,
                "code_str": code_str
            }

            # 记录任务开始时间
            start_time = time.time()
            
            # 首先调用Plan Agent进行代码分析和任务规划
            print(f"[Debug] 开始调用Plan Agent进行代码分析和任务规划")
            try:
                # 传递完整的文件路径，而不仅仅是文件名
                input_file_name = code_file_path  # 使用完整路径
                # 使用为Plan Agent配置的模型
                plan_model = AGENT_MODELS.get("plan", api_client.model) if api_client.model_type == "online" else local_model
                plan_result = await handle_plan_task(code_str, api_client, plan_model, input_file_name, args.force_local_tools)
                
                # 将Plan Agent的分析结果添加到上下文中
                context_base["plan_facts"] = plan_result["facts"]
                
                # 添加统计信息到上下文
                if "statistics" in plan_result:
                    context_base["statistics"] = plan_result["statistics"]
                    stats = plan_result["statistics"]
                    print(f"[Debug] 加载了缺陷统计信息: {stats.get('total_defects', 0)} 个缺陷，涉及 {stats.get('total_variables', 0)} 个变量")
                
                try:
                    expert_judge_data = json.loads(plan_result["expert_judge_json"])
                    context_base["expert_judge_tasks"] = expert_judge_data.get("expert_judge_tasks", [])
                    
                    # 打印任务信息
                    task_count = len(context_base["expert_judge_tasks"])
                    var_count = sum(len(task.get("sharedVariables", [])) for task in context_base["expert_judge_tasks"])
                    print(f"[Debug] 加载了 {task_count} 个expert-judge任务，涉及 {var_count} 个共享变量")
                except Exception as e:
                    print(f"[Warning] 解析expert-judge任务失败: {str(e)}")
                    context_base["expert_judge_tasks"] = []
                
                # 保存Plan Agent的分析结果到文件
                plan_result_file = response_file_base.replace(".txt", "-plan.json")
                with open(plan_result_file, "w") as f:
                    json.dump(plan_result, f, indent=2, ensure_ascii=False)
                    
                # 单独保存两轮输出到文件
                tool_plan_file = response_file_base.replace(".txt", "-tool-plan.xml")
                with open(tool_plan_file, "w") as f:
                    f.write(plan_result["tool_plan_text"])
                    
                expert_judge_file = response_file_base.replace(".txt", "-expert-judge-plan.json")
                with open(expert_judge_file, "w") as f:
                    f.write(plan_result["expert_judge_json"])
                    
                print(f"[Debug] Plan Agent分析结果已保存到: {plan_result_file}")
                print(f"[Debug] 工具计划已保存到: {tool_plan_file}")
                print(f"[Debug] Expert-Judge计划已保存到: {expert_judge_file}")
            except Exception as e:
                print(f"[Error] Plan Agent分析失败: {str(e)}")
                import traceback
                print(traceback.format_exc())
                # 继续执行，但不使用Plan Agent的结果

            # 检查是否有有效的expert-judge任务需要执行
            use_workflow_manager = False
            workflow_tasks = []
            
            try:
                if plan_result and plan_result.get("expert_judge_json"):
                    expert_judge_data = json.loads(plan_result["expert_judge_json"])
                    # 检查两种可能的任务键名：tasks（WorkflowManager期望）和expert_judge_tasks（PlanAgent生成）
                    workflow_tasks = expert_judge_data.get("tasks", [])
                    if not workflow_tasks:
                        workflow_tasks = expert_judge_data.get("expert_judge_tasks", [])
                    
                    # 检查任务是否有效（非空且有必要的字段）
                    valid_tasks = []
                    for task in workflow_tasks:
                        # 检查任务是否有必要的字段
                        if (task.get("pattern") and task.get("variables")) or \
                           (task.get("accessPattern") and task.get("sharedVariables")):
                            valid_tasks.append(task)
                    
                    if valid_tasks:
                        use_workflow_manager = True
                        print(f"[Debug] 发现 {len(valid_tasks)} 个有效的expert-judge任务，使用WorkflowManager执行")
                    else:
                        print(f"[Debug] 没有发现有效的expert-judge任务，回退到传统缺陷模式处理")
                        print(f"[Debug] 任务数据: {workflow_tasks}")
                else:
                    print(f"[Debug] Plan Agent未生成expert-judge任务，回退到传统缺陷模式处理")
            except Exception as e:
                print(f"[Warning] 解析expert-judge任务失败: {str(e)}，回退到传统缺陷模式处理")
                use_workflow_manager = False

            # 选择执行路径：WorkflowManager 或 传统缺陷模式处理
            if use_workflow_manager:
                # === 使用 WorkflowManager 执行 expert-judge 任务 ===
                print(f"[Debug] 开始使用WorkflowManager执行expert-judge任务")
                
                try:
                    # 为Expert和Judge Agent选择模型
                    expert_judge_model = None
                    if api_client.model_type == "online":
                        expert_judge_model = AGENT_MODELS.get("plan", api_client.model)
                    else:
                        expert_judge_model = local_model
                    
                    # 创建WorkflowManager
                    workflow_manager = create_workflow_manager(api_client, expert_judge_model)
                    
                    # 设置workflow
                    allocated_tasks = workflow_manager.setup_workflow(plan_result["expert_judge_json"])
                    print(f"[Debug] WorkflowManager已分配 {len(allocated_tasks)} 个任务")
                    
                    # 准备执行上下文
                    execution_context = {
                        "code": code_str,
                        "operations": context_base.get("operations", {}),
                        "facts": context_base.get("plan_facts", {}),
                        "file_path": code_file_path
                    }
                    
                    # 执行所有任务
                    print(f"[Debug] 开始并行执行所有expert-judge任务")
                    workflow_result = await workflow_manager.execute_all_tasks(execution_context)
                    
                    # 保存WorkflowManager执行结果
                    workflow_result_file = response_file_base.replace(".txt", "-workflow-result.json")
                    workflow_result_data = {
                        "total_tasks": workflow_result.total_tasks,
                        "completed_tasks": workflow_result.completed_tasks,
                        "failed_tasks": workflow_result.failed_tasks,
                        "results": workflow_result.results,
                        "errors": workflow_result.errors
                    }
                    
                    with open(workflow_result_file, "w", encoding='utf-8') as f:
                        json.dump(workflow_result_data, f, indent=2, ensure_ascii=False)
                    
                    print(f"[Debug] WorkflowManager执行完成:")
                    print(f"  - 总任务数: {workflow_result.total_tasks}")
                    print(f"  - 完成任务数: {workflow_result.completed_tasks}")
                    print(f"  - 失败任务数: {workflow_result.failed_tasks}")
                    print(f"  - 结果保存到: {workflow_result_file}")
                    
                    # 跳过传统的缺陷模式处理
                    tasks = []
                    
                except Exception as e:
                    print(f"[Error] WorkflowManager执行失败: {str(e)}")
                    import traceback
                    print(traceback.format_exc())
                    print(f"[Debug] 回退到传统缺陷模式处理")
                    use_workflow_manager = False
            
            if not use_workflow_manager:
                # === 传统缺陷模式处理 ===
                # 异步处理所有缺陷模式任务
                tasks = []
                print(f"[Debug] 开始创建异步任务，数量={len(found_defect_modes)}，单个任务超时限制: 10000秒")
                
                # 启用批量处理模式
                batch_processing = True if api_client.model_type == "local" and len(found_defect_modes) > 1 else False
                
                # 为Expert和Judge Agent选择模型
                expert_judge_model = None
                if api_client.model_type == "online":
                    # 使用为Expert和Judge配置的模型
                    expert_judge_model = AGENT_MODELS.get("plan", api_client.model)
                else:
                    expert_judge_model = local_model
                
                if batch_processing:
                    print(f"[Debug] 启用批量处理模式，将 {len(found_defect_modes)} 个缺陷模式分析任务批量提交")
                    # 批量处理模式
                    # 准备所有任务的上下文
                    all_tasks_contexts = []
                    all_defect_modes = []
                    
                    for defect_mode in found_defect_modes:
                        pattern_response_file = response_file_base.replace(".txt", f"-{defect_mode}.txt")
                        context = context_base.copy()
                        context["response_file_path"] = pattern_response_file
                        all_tasks_contexts.append(context)
                        all_defect_modes.append(defect_mode)
                    
                    # 创建批量处理任务
                    batch_task = handle_batch_tasks(all_defect_modes, all_tasks_contexts, api_client, expert_judge_model, start_time)
                    task = asyncio.create_task(batch_task)
                    task.set_name(f"batch_tasks_{len(found_defect_modes)}")
                    timeout_task = asyncio.wait_for(task, timeout=10000)
                    tasks.append(timeout_task)
                else:
                    # 原有的单任务处理模式
                    for defect_mode in found_defect_modes:
                        pattern_response_file = response_file_base.replace(".txt", f"-{defect_mode}.txt")
                        context = context_base.copy()
                        context["response_file_path"] = pattern_response_file
                        
                        # 创建基础任务
                        base_task = handle_pattern_task(defect_mode, context, api_client, expert_judge_model, start_time)
                        
                        # 先将协程包装为任务，再设置超时和名称
                        task = asyncio.create_task(base_task)
                        task.set_name(f"task_{defect_mode}")
                        
                        # 对任务应用超时控制
                        timeout_task = asyncio.wait_for(task, timeout=10000)
                        tasks.append(timeout_task)

                # 等待所有任务完成
                print(f"[Debug] 等待{len(tasks)}个任务完成...")
                for task in asyncio.as_completed(tasks):
                    try:
                        result = await task
                        if result:
                            results.append(result)
                            print(f"[Completed] Defect mode: {result[0]}")
                    except asyncio.TimeoutError:
                        # 超时由任务内部的CancelledError处理，此处仅记录
                        print(f"[Timeout] 任务已超时，结果已保存")
                    except Exception as e:
                        print(f"[Error] 处理任务时发生错误: {str(e)}")
                        import traceback
                        print(traceback.format_exc())
            else:
                # 如果使用WorkflowManager，确保tasks为空列表以避免后续处理错误
                tasks = []

            # 计算耗时并更新日志
            time_taken = time.time() - start_time
            max_time = max(max_time, time_taken)
            print(f"[Iteration completed] i={i}, 耗时: {time_taken:.2f}s")
            
            # 打印API密钥状态
            if api_client.model_type == "online":
                api_client.print_api_keys_status()
            
            with open(log_file_path, "a") as log_file:
                log_file.write(f"Iteration i={i}: Time taken {time_taken:.2f}s, Max time {max_time:.2f}s\n")

    finally:
        # 释放模型资源
        if local_model:
            print(f"[Debug] 释放模型资源")
            try:
                await local_model.close()
                print(f"[Debug] 本地模型资源已释放")
            except Exception as e:
                print(f"[Error] 释放模型资源失败: {str(e)}")

    print(f"[All tasks completed] Max time: {max_time:.2f}s")
    with open(log_file_path, "a") as log_file:
        log_file.write(f"Maximum time across all tasks: {max_time:.2f}s\n")

if __name__ == "__main__":
    print(f"[Debug] 程序开始执行，Python版本={__import__('sys').version}")
    asyncio.run(main())